// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUV2r9LrIMBnQKu3g_0w27CRntXYK04fQ',
    appId: '1:813870519087:web:235da190a0b2efe40c87da',
    messagingSenderId: '813870519087',
    projectId: 'chokotto-memo-app',
    authDomain: 'chokotto-memo-app.firebaseapp.com',
    storageBucket: 'chokotto-memo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHHv5m4qZauQcWzm7dUUHcOeMtlB-kjAw',
    appId: '1:813870519087:android:d7435fffd62a96c80c87da',
    messagingSenderId: '813870519087',
    projectId: 'chokotto-memo-app',
    storageBucket: 'chokotto-memo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZDE_U6mwzRYBlWxPxO6x4OPCpXZjIpM',
    appId: '1:813870519087:ios:1459fbcf683602140c87da',
    messagingSenderId: '813870519087',
    projectId: 'chokotto-memo-app',
    storageBucket: 'chokotto-memo-app.appspot.com',
    iosClientId: '813870519087-bvl3ievt65g84vu4cv1vk7o9s0nudnst.apps.googleusercontent.com',
    iosBundleId: 'com.11tatsumimn08.flutterFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZDE_U6mwzRYBlWxPxO6x4OPCpXZjIpM',
    appId: '1:813870519087:ios:0877cd27e1cefc640c87da',
    messagingSenderId: '813870519087',
    projectId: 'chokotto-memo-app',
    storageBucket: 'chokotto-memo-app.appspot.com',
    iosClientId: '813870519087-t23pa0thdm2u9g3kee9tb0o7pil7uraa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirstApp',
  );
}
